### ISSUE TITLE
have a complate version?

### ISSUE THREAD

**Issue by gnineh** [yupferris/fuse-example-video-login-screen#1]
how create this .ux file?

**Comment by yupferris** [comment]
I'm not sure what you're asking. Have you seen the [video](https://www.youtube.com/watch?v=zfiz-yI4VWY&feature=youtu.be)?

If you need help creating Fuse projects, you should check out the [tutorial](https://www.fusetools.com/learn/guides/tutorial) :)

**Comment by gnineh** [comment]
@yupferris 哈哈。
