### ISSUE TITLE
Could not resolve type 'video'

### ISSUE THREAD

**Issue by rahul606** [yupferris/fuse-example-video-login-screen#2]
Adding video files as mentioned is not working.

**Comment by yupferris** [comment]
Hey there, can you post some of your code so I can understand your problem better?

**Comment by rahul606** [comment]
In mainview.ux of this example I am trying to add a video background like this <video File="Asstes/video.mp4" AutoPlay="true" IsLooping="true" Layer="Background" /> But I am having an error as mentioned in the issue

**Comment by rahul606** [comment]
> <video

 File="Asstes/video.mp4" AutoPlay="true" IsLooping="true" Layer="Background" 

> />

This is what I am trying.

**Comment by yupferris** [comment]
I believe the problem is you used lowercase `video` instead of `Video`. Can you try it with a capital `V` and let me know how it goes?

**Comment by rahul606** [comment]
OMG I am such an ... anyways thx for the quick reply .... really appreciate it.

**Comment by yupferris** [comment]
No problem, glad to help :)
